info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/get_user_list:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: json
      tags:
      - GetUserList
swagger: "2.0"
